[config][xs]: change country results sheet as getting csv error with current one.
Error: Invalid closing quote at line 1; found "E" instead of delimiter ","

Fixed by changing from (gid=0) sheet:

https://docs.google.com/spreadsheet/pub?key=0Ak6K0pSAyW1gdFpGRWhWd1lSeXNFX0dMRGw2VEFvSXc&single=true&gid=0

to (gid=7) sheet: https://docs.google.com/spreadsheet/pub?key=0Ak6K0pSAyW1gdFpGRWhWd1lSeXNFX0dMRGw2VEFvSXc&single=true&gid=7